# Generated by Django 5.0.4 on 2024-10-06 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lessonName', models.CharField(max_length=100)),
                ('lessonOrder', models.CharField(max_length=100)),
                ('lessonDescription', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=100)),
                ('translation', models.CharField(max_length=100)),
                ('note', models.CharField(blank=True, max_length=300, null=True)),
                ('order', models.CharField(blank=True, max_length=20, null=True)),
                ('brokenDownPhrase', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('unitName', models.CharField(max_length=100)),
                ('unitDescription', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CustomSlide',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('normalComponentType', models.CharField(choices=[('i', 'Intro'), ('m', 'MultipleChoice'), ('t', 'TwoMultipleChoice'), ('y', 'TrueFalse'), ('b', 'BuildBlock'), ('f', 'Fill In Blank'), ('p', 'MatchPairs'), ('x', 'TextWrite'), ('d', 'Dialogue'), ('n', 'Note')], max_length=1)),
                ('prompt', models.CharField(default='', max_length=200)),
                ('options', models.CharField(blank=True, max_length=500, null=True)),
                ('answer', models.CharField(default='', max_length=300)),
                ('dialogue', models.CharField(blank=True, max_length=1000, null=True)),
                ('audio', models.CharField(default='', max_length=300)),
                ('lesson', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=60)),
                ('note', models.TextField(max_length=1000)),
                ('audio', models.CharField(blank=True, max_length=300, null=True)),
                ('lesson', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='api.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(default='', max_length=100)),
                ('translation', models.CharField(default='', max_length=100)),
                ('note', models.CharField(blank=True, max_length=300, null=True)),
                ('order', models.CharField(default='', max_length=100)),
                ('brokenDownSentence', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('containedPhrases', models.ManyToManyField(blank=True, to='api.phrase')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slideType', models.CharField(choices=[('i', 'Intro'), ('m', 'MultipleChoice'), ('t', 'TwoMultipleChoice'), ('y', 'TrueFalse'), ('b', 'BuildBlock'), ('f', 'Fill In Blank'), ('p', 'MatchPairs'), ('x', 'TextWrite'), ('d', 'Dialogue'), ('n', 'Note')], max_length=1)),
                ('prompt', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('options', models.CharField(blank=True, max_length=500, null=True)),
                ('answer', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('dialogue', models.CharField(blank=True, max_length=1000, null=True)),
                ('audio', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('video', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('image', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.lesson')),
                ('note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.note')),
                ('phrase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.phrase')),
                ('sentence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.sentence')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='api.unit'),
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=100)),
                ('translation', models.CharField(max_length=100)),
                ('note', models.CharField(blank=True, max_length=300, null=True)),
                ('relatedWords', models.ManyToManyField(blank=True, to='api.word')),
            ],
        ),
        migrations.AddField(
            model_name='sentence',
            name='containedWords',
            field=models.ManyToManyField(blank=True, to='api.word'),
        ),
        migrations.AddField(
            model_name='phrase',
            name='containedWords',
            field=models.ManyToManyField(to='api.word'),
        ),
    ]
