# Generated by Django 5.0.4 on 2024-06-18 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lessonName', models.CharField(max_length=100)),
                ('lessonType', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('unitName', models.CharField(max_length=100)),
                ('unitDescription', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=40)),
                ('note', models.CharField(max_length=100)),
                ('lesson', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='api.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=100)),
                ('phraseTranslation', models.CharField(max_length=100)),
                ('phraseNote', models.CharField(blank=True, max_length=300, null=True)),
                ('brokenDownPhrase', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('relatedPhrases', models.ManyToManyField(blank=True, to='api.phrase')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='phrase',
            field=models.ManyToManyField(default='', to='api.phrase'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='api.unit'),
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=100)),
                ('wordTranslation', models.CharField(max_length=100)),
                ('wordNote', models.CharField(blank=True, max_length=300, null=True)),
                ('relatedWords', models.ManyToManyField(blank=True, to='api.word')),
            ],
        ),
        migrations.AddField(
            model_name='phrase',
            name='containedWords',
            field=models.ManyToManyField(to='api.word'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='words',
            field=models.ManyToManyField(blank=True, to='api.word'),
        ),
    ]
