# Generated by Django 5.0.4 on 2024-06-18 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_sentence'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='containedWords',
            field=models.ManyToManyField(blank=True, null=True, to='api.word'),
        ),
        migrations.AddField(
            model_name='sentence',
            name='order',
            field=models.CharField(default='', max_length=100),
        ),
    ]
