# Generated by Django 5.0.4 on 2024-10-06 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_slide_new'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlideNew',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slideType', models.CharField(choices=[('i', 'Intro'), ('m', 'MultipleChoice'), ('t', 'TwoMultipleChoice'), ('y', 'TrueFalse'), ('b', 'BuildBlock'), ('f', 'Fill In Blank'), ('p', 'MatchPairs'), ('x', 'TextWrite'), ('d', 'Dialogue'), ('n', 'Note')], max_length=1)),
                ('prompt', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('options', models.CharField(blank=True, max_length=500, null=True)),
                ('answer', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('dialogue', models.CharField(blank=True, max_length=1000, null=True)),
                ('audio', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('video', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('image', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.lesson')),
                ('note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.note')),
                ('otherPhrases', models.ManyToManyField(blank=True, null=True, related_name='other_phrases', to='api.phrase')),
                ('phrase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.phrase')),
                ('sentence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.sentence')),
            ],
        ),
    ]
