# Generated by Django 5.0.4 on 2024-10-06 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_slidenew'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SlideNew',
        ),
    ]
