# Generated by Django 5.0.4 on 2024-06-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_sentence_containedphrases_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lessonDescription',
            field=models.CharField(default='', max_length=300),
        ),
    ]
