# Generated by Django 5.0.4 on 2024-10-06 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_delete_slidenew'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='otherPhrases',
            field=models.ManyToManyField(blank=True, null=True, related_name='other_phrases', to='api.phrase'),
        ),
    ]
