# Generated by Django 5.0.4 on 2024-07-21 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_lesson_lessondescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSlide',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('normalComponentType', models.CharField(choices=[('i', 'Intro'), ('m', 'MultipleChoice'), ('y', 'TrueFalse'), ('b', 'BuildBlock'), ('f', 'fill'), ('p', 'MatchPairs'), ('x', 'TextWrite'), ('d', 'Dialogue')], max_length=1)),
                ('prompt', models.CharField(default='', max_length=200)),
                ('options', models.CharField(blank=True, max_length=500, null=True)),
                ('answer', models.CharField(default='', max_length=300)),
                ('dialogue', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
