# Generated by Django 5.0.4 on 2024-07-29 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_customslide'),
    ]

    operations = [
        migrations.AddField(
            model_name='customslide',
            name='lesson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.lesson'),
        ),
    ]
