# Generated by Django 5.0.4 on 2024-08-06 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_customslide_audio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('normalComponentType', models.CharField(choices=[('i', 'Intro'), ('m', 'MultipleChoice'), ('y', 'TrueFalse'), ('b', 'BuildBlock'), ('f', 'FillinBlank'), ('p', 'MatchPairs'), ('x', 'TextWrite'), ('d', 'Dialogue')], max_length=1)),
                ('prompt', models.CharField(default='', max_length=200)),
                ('options', models.CharField(blank=True, max_length=500, null=True)),
                ('answer', models.CharField(default='', max_length=300)),
                ('dialogue', models.CharField(blank=True, max_length=1000, null=True)),
                ('audio', models.CharField(default='', max_length=300)),
                ('Sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sentence')),
                ('lesson', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.lesson')),
                ('phrase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.phrase')),
            ],
        ),
    ]
