# Generated by Django 5.0.4 on 2024-08-06 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_slide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='Sentence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.sentence'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='answer',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='slide',
            name='audio',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='slide',
            name='prompt',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
