# Generated by Django 5.0.4 on 2024-08-06 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_slide_sentence_alter_slide_answer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='lessonType',
            new_name='lessonOrder',
        ),
        migrations.RenameField(
            model_name='phrase',
            old_name='phraseNote',
            new_name='note',
        ),
        migrations.RenameField(
            model_name='phrase',
            old_name='phraseTranslation',
            new_name='translation',
        ),
        migrations.RenameField(
            model_name='sentence',
            old_name='sentenceNote',
            new_name='note',
        ),
        migrations.RenameField(
            model_name='sentence',
            old_name='sentenceTranslation',
            new_name='translation',
        ),
    ]
