# Generated by Django 5.0.4 on 2024-08-06 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_lessontype_lesson_lessonorder_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slide',
            old_name='normalComponentType',
            new_name='slideType',
        ),
    ]
