# Generated by Django 5.0.4 on 2024-08-06 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_sentence_slide_sentence_slide_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='slideType',
            field=models.CharField(choices=[('i', 'Intro'), ('m', 'MultipleChoice'), ('y', 'TrueFalse'), ('b', 'BuildBlock'), ('f', 'fill'), ('p', 'MatchPairs'), ('x', 'TextWrite'), ('d', 'Dialogue')], max_length=1),
        ),
    ]
