# Generated by Django 5.0.4 on 2024-08-07 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_customslide_lesson_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customslide',
            name='lesson',
        ),
        migrations.AlterField(
            model_name='slide',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.lesson'),
        ),
        migrations.RemoveField(
            model_name='slide',
            name='phrase',
        ),
        migrations.AddField(
            model_name='customslide',
            name='lesson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.lesson'),
        ),
        migrations.AddField(
            model_name='slide',
            name='phrase',
            field=models.ManyToManyField(to='api.phrase'),
        ),
    ]
