# Generated by Django 5.0.4 on 2024-08-09 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_note_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='wordNote',
            new_name='note',
        ),
        migrations.RenameField(
            model_name='word',
            old_name='wordTranslation',
            new_name='translation',
        ),
    ]
