# Generated by Django 5.0.4 on 2024-10-06 19:58

import datetime
import django.db.models.deletion
import progress.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('streak', models.IntegerField(default=0)),
                ('lastUpdate', models.DateField(blank=True, default=datetime.datetime.now)),
                ('lastLesson', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.lesson')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PhraseProgress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('masteryLevel', progress.models.IntegerRangeField(default=0, null=True)),
                ('phrase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.phrase')),
                ('progressObj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progress.progress')),
            ],
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('completed', models.BooleanField(default=False)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.lesson')),
                ('progressObj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progress.progress')),
            ],
        ),
        migrations.CreateModel(
            name='SentenceProgress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('masteryLevel', progress.models.IntegerRangeField(default=0, null=True)),
                ('progressObj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progress.progress')),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sentence')),
            ],
        ),
        migrations.CreateModel(
            name='WordProgress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('masteryLevel', progress.models.IntegerRangeField(default=0, null=True)),
                ('progressObj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progress.progress')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.word')),
            ],
        ),
    ]
