# Generated by Django 5.0.4 on 2024-06-25 01:05

import django.db.models.deletion
import progress.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0004_sentence_lesson'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('streak', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PhraseProgress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('masteryLevel', progress.models.IntegerRangeField()),
                ('phrase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.phrase')),
                ('progressObj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progress.progress')),
            ],
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('completed', models.IntegerField(default=0)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.phrase')),
                ('progressObj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progress.progress')),
            ],
        ),
        migrations.CreateModel(
            name='SentenceProgress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('masteryLevel', progress.models.IntegerRangeField()),
                ('progressObj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progress.progress')),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sentence')),
            ],
        ),
        migrations.CreateModel(
            name='WordProgress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('masteryLevel', progress.models.IntegerRangeField()),
                ('progressObj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progress.progress')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.phrase')),
            ],
        ),
    ]
