# Generated by Django 5.0.4 on 2024-06-25 12:34

import progress.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phraseprogress',
            name='masteryLevel',
            field=progress.models.IntegerRangeField(default=0, null=True),
        ),
    ]
