# Generated by Django 5.0.4 on 2024-06-25 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_sentence_lesson'),
        ('progress', '0002_alter_phraseprogress_masterylevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordprogress',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.word'),
        ),
    ]
