# Generated by Django 5.0.4 on 2024-06-25 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_sentence_lesson'),
        ('progress', '0003_alter_wordprogress_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonprogress',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.lesson'),
        ),
    ]
