# Generated by Django 5.0.4 on 2024-06-25 14:41

import progress.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0004_alter_lessonprogress_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentenceprogress',
            name='masteryLevel',
            field=progress.models.IntegerRangeField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='wordprogress',
            name='masteryLevel',
            field=progress.models.IntegerRangeField(default=0, null=True),
        ),
    ]
