# Generated by Django 5.0.4 on 2024-06-27 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_sentence_containedphrases_and_more'),
        ('progress', '0006_progress_lastupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='lastLesson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.lesson'),
        ),
    ]
