# Generated by Django 5.0.4 on 2024-06-29 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0007_progress_lastlesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonprogress',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
